# excerpt_separator: ""
# pygments: true
# markdown: kramdown
# url: http://ver2point0.github.io
# google_analytics: "UA-74207113-1"
# title: John McIntosh II
# email: jmci10@hotmail.com
# author: John McIntosh II
# description: My personal portfolio and blog.
# paginate: 5
